{% set name = "reprexpy" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8feca3d2ae8a7173fe19152396a0fa14fe03cd36ff38e403b13f897b7dff12bc

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv'

requirements:
  host:
    - pip
    - python >=3.6
    # This currently a hard dependency on installation.
    # Can be removed once https://github.com/crew102/reprexpy/pull/3 is merged
    - pytest-runner
  run:
    - asttokens
    - ipykernel
    - ipython
    - matplotlib-base
    - nbconvert
    - nbformat
    - pyimgur
    - pyperclip
    - python >=3.6
    - setuptools
    - stdlib-list
    - tornado <=5.1.1

test:
  imports:
    - reprexpy

about:
  home: https://reprexpy.readthedocs.io/en/latest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Render reproducible examples of Python code (port of R package `reprex`)
  dev_url: https://github.com/crew102/reprexpy

extra:
  recipe-maintainers:
    - xhochy
