travis:
  secure:
    BINSTAR_TOKEN: XX0vWCkpMfcbklKp2TKDh6l0XNhq/zayRDNq6haeU7av/Dvoc7Bx8Sm8rz5nB9LJ4hmoVZGHPwJ+LFjgF+KYie80ygI1uekXqUI97HjymrSQlBakBUqMs/Ar5TUoXxGziDesRSVq6X54R9JrIvom3XbNqClCPJUKlr6Y3eAAZ6ltcSaGY5+dXc4S5lY8KqEMKFxFksuNP84Y0v/L42t7pQmDxZ15XGuujtKqeAtBJ391N5V4Cpn9J2WIBRMkHEijze2cMCmzWC0SihaJj/c/nss18quidXHI8vflkiSZ33vKzEpt1gQhda60y6yJgNoYETZFo8st0SS9ikA81UkFBYmHpwW4auGYmkSSgNgQvLFRrMSOMU/VS/Tti9ImqVMQ+ECZV23ZIMg2ZzDpr9NvAuXbDdB7gamuowvTYRRCFk0gqIe/3IugqkEYeQuhsNYi2N8wQ8V8V85aBTGgR1pawMF6nn8t0bL5QKKEbRmJI1UvqqQTcTOx2Hl1Cla6ONcAG8n350KzkVV5v/9r6DmHwkpADLdqUkVKxqBU6xbUwKQ2LoyVEfD3VEACE7toi3081B1mrN4MX6XaosCP+QXI099gxIvtufFfR2h4s22gLQDfOAq61JP01FIXTYvKHPKMJz2R6I8mH60pHEPHEq3ItKlyQNvWED5qtYbA6TKPKZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
